services:
  - type: web
    name: x-cancer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k uvicorn.workers.UvicornWorker backend.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
  - type: static
    name: x-cancer-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: x-cancer-api
          property: host
